name: kenali_vaksin
description: Know more about vaccines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/assets/sinovac.png
    - images/assets/biofarma.png
    - images/assets/astrazeneca.png
    - images/assets/sinopharm.png
    - images/assets/moderna.png
    - images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

flutter_icons:
  image_path: "images/icon.png"
  android: true
  adaptive_icon_background: "#ffffff"